#!/usr/bin/env python3
"""Render docs/index.html from docs/template.html + docs/content.yaml.

Workflow: edit the copy in content.yaml, run `python3 docs/build.py`, refresh
the page. The template holds the markup and the interactive code; the YAML holds
all the words.

Two small conveniences in the YAML:
  - markdown-lite: **bold** -> <b>, `code` -> <span class="mono">…</span>
    (raw HTML in a value still passes through untouched)
  - the `dynamic:` block is the copy the page fills in live (slider/click
    readouts); it's serialized to JSON and injected into the page's CONTENT
    variable. {curly} placeholders in those strings are filled at runtime.
"""
import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

HERE = Path(__file__).resolve().parent


def md_lite(s):
    s = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", s)
    s = re.sub(r"`(.+?)`", r'<span class="mono">\1</span>', s)
    return s


def walk(x):
    """Apply markdown-lite to every string leaf, preserving structure."""
    if isinstance(x, str):
        return md_lite(x)
    if isinstance(x, list):
        return [walk(v) for v in x]
    if isinstance(x, dict):
        return {k: walk(v) for k, v in x.items()}
    return x


def flatten(d, prefix=""):
    out = {}
    for k, v in d.items():
        key = f"{prefix}{k}"
        if isinstance(v, dict):
            out.update(flatten(v, key + "."))
        else:
            out[key] = v
    return out


def main():
    content = yaml.safe_load((HERE / "content.yaml").read_text())
    template = (HERE / "template.html").read_text()

    # dynamic copy -> the page's CONTENT variable (markdown-lite applied)
    dynamic = walk(content.pop("dynamic", {}))
    template = template.replace(
        "{{__CONTENT_JSON__}}", json.dumps(dynamic, ensure_ascii=False)
    )

    # static copy -> {{dotted.key}} placeholders (markdown-lite applied)
    flat = flatten(walk(content))

    def sub(m):
        key = m.group(1).strip()
        if key not in flat:
            sys.exit(f"content.yaml has no key '{key}' (used in template.html)")
        return str(flat[key])

    html = re.sub(r"\{\{\s*([\w.]+)\s*\}\}", sub, template)

    leftover = re.findall(r"\{\{.*?\}\}", html)
    if leftover:
        sys.exit(f"unfilled placeholders left in output: {leftover}")

    banner = ("<!-- GENERATED by docs/build.py from template.html + "
              "content.yaml. Do not edit this file directly; edit the copy in "
              "content.yaml and re-run: python3 docs/build.py -->\n")
    html = html.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + banner, 1)

    (HERE / "index.html").write_text(html)
    print(f"wrote {HERE / 'index.html'} ({len(html):,} bytes)")


if __name__ == "__main__":
    main()
